# Generated by Django 5.2.5 on 2025-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpost',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='title',
            field=models.CharField(default='Post Title', max_length=255),
        ),
    ]
