# Generated by Django 5.2.5 on 2025-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_analyzer', '0004_alertsettings_savedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
