# Generated by Django 5.2.5 on 2025-08-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_analyzer', '0005_socialpost_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='location',
        ),
    ]
